### ISSUE TITLE
tried this, but it simply doesn't work

### ISSUE THREAD

**Issue by silky** [mafintosh/webcat#3]
no error message, nothing.

i type "webcat [foo]" and foo does the same for me "webcat silky", the program stays up, and we type things, but we never see what we are typing on the others screen.

**Comment by reqshark** [comment]
ya I think right now only @mafintosh and maybe @maxogden know how this actually works

**Comment by mafintosh** [comment]
@silky what version are you using? fixed a bunch of stuff in 1.1.2

**Comment by silky** [comment]
i'm using the version on npm

```
02:43 PM noon ∈ ~>webcat --version
Usage: webcat receivers-github-username
```

**Comment by silky** [comment]
i've installed the version from this repo with `npm install .` and done this

```
02:53 PM noon ∈ webcat@master>webcat mafintosh  
sup

```

left the terminal open. try writing something back?

**Comment by reqshark** [comment]
try reqshark

**Comment by silky** [comment]
ah, it just died with

```
events.js:72                                                                               
        throw er; // Unhandled 'error' event                                               
              ^                                                                            
Error: Failed to set local answer sdp: Failed to push down transport description: Failed to apply remote fingerprint.                                                                 
```

tried reqshark, nothing ...

edit: just died

```
02:59 PM noon ∈ webcat@master>webcat reqshark
sup
sup


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:
140316696184704:error:0407006A:rsa routines:RSA_padding_check_PKCS1_type_1:block type is not 01:../deps/openssl/openssl/crypto/rsa/rsa_pk1.c:100:
140316696184704:error:04067072:rsa routines:RSA_EAY_PUBLIC_DECRYPT:padding check failed:../deps/openssl/openssl/crypto/rsa/rsa_eay.c:721:

    at SlabBuffer.use (tls.js:232:18)
    at CleartextStream.read [as _read] (tls.js:450:29)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at tls.js:514:14
    at process._tickCallback (node.js:415:13)

```

**Comment by reqshark** [comment]
what's your OS btw, osx?

**Comment by silky** [comment]
ubuntu:

```
03:05 PM noon ∈ ~>uname -a
Linux qma 3.11.0-26-generic #45-Ubuntu SMP Tue Jul 15 04:02:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by reqshark** [comment]
wow you got it to install on linux? 

it doesnt work on my linux, you need osx at this point, i think

try one more time but upgrade your iojs to v1.7.1 (that's what i use for now) and your pkg to 1.1.2.

**Comment by silky** [comment]
i'll have to attempt this later, installing 1.7.1 is going to take a bit of time.

**Comment by reqshark** [comment]
no it's dumb quick, just use [nvm](https://github.com/creationix/nvm)

**Comment by silky** [comment]
damnit, nah, `nvm` just failed to install because it incorrectly identified me as using bash when i use zsh.

i'll have to debug all this later.

-- edit: actually, fixed it, something is happening.

```
03:36 PM noon ∈ ~>nvm install iojs v1.7.1 
######################################################################## 100.0%
WARNING: checksums are currently disabled for io.js
Now using io.js v1.7.1
```

however

```
03:37 PM noon ∈ ~>nvm install pkg v1.1.2 
Version 'pkg' not found - try `nvm ls-remote` to browse available versions.
```

**Comment by silky** [comment]
also

```
03:40 PM noon ∈ ~>npm install pkg@1.1.2
npm WARN package.json iojs@1.0.0 No repository field.
npm http GET https://registry.npmjs.org/pkg/1.1.2
npm http 404 https://registry.npmjs.org/pkg/1.1.2
npm ERR! Error: version not found: 1.1.2 : pkg/1.1.2
npm ERR!     at RegClient.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:272:14)
npm ERR!     at Request.self.callback (/usr/local/lib/node_modules/npm/node_modules/request/index.js:148:22)
npm ERR!     at Request.EventEmitter.emit (events.js:98:17)
npm ERR!     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:891:14)
npm ERR!     at Request.EventEmitter.emit (events.js:117:20)
npm ERR!     at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/request/index.js:842:12)
npm ERR!     at IncomingMessage.EventEmitter.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:920:16
npm ERR!     at process._tickCallback (node.js:415:13)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.11.0-26-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "pkg@1.1.2"
npm ERR! cwd /home/noon
npm ERR! node -v v0.10.18
npm ERR! npm -v 1.3.8
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/noon/npm-debug.log
npm ERR! not ok code 0
```

oh well.

**Comment by reqshark** [comment]
oh woops i meant install this pkg at 1.1.2+, meaning:

``` bash
$ npm i -g webcat
```

whatever, getting back to nvm, you should still be able to source that file into your shell, i always install using git and add something like `source $HOME/.nvm/nvm.sh` to my `.profile`

i use [bash with an informative git prompt](https://github.com/reqshark/bash-git-prompt), personally, but the important things I tend do would go something like:

``` bash
cd && git clone https://github.com/creationix/nvm.git .nvm
echo -e "source ~/.nvm/nvm.sh" >> ".bashrc"
```

since you use zsh you might even have to do it like:

``` bash
git clone https://github.com/creationix/nvm.git ~/.nvm
echo -e "source $HOME/.nvm/nvm.sh" >> "$HOME/.profile"
```

.. or i don't know, some variation of which your shell is receptive

also I'm going to sleep now but I will be on the internet when i wake up

![internet](https://cloud.githubusercontent.com/assets/937826/7196723/216c13d0-e4a5-11e4-8486-9f0babb9cf00.jpg)

**Comment by silky** [comment]
i installed webcat at 1.1.2 now using what you said (not with `-g` though)

and yeah, i just copied the changes it made to .bashrc into my zshrc and it worked fine

**Comment by mafintosh** [comment]
@silky did webcat work?

**Comment by silky** [comment]
```
04:27 PM noon ∈ ~>webcat mafintosh
i don't know

```

```
04:28 PM noon ∈ ~>webcat --version
1.2.1
```

**Comment by mafintosh** [comment]
@silky try rerunning it with `DEBUG=* webcat mafintosh` and post the output here

**Comment by silky** [comment]
```
noon ∈ ~>DEBUG=* webcat mafintosh 
  webcat new instance +0ms mafintosh { _: [ 'mafintosh' ], username: 'silky' }
  webcat signing message +8ms { type: 'syn', nouce: 0.365207004128024 }
sup

```

**Comment by mafintosh** [comment]
@silky i got your `sup`!! - did you ctrl-c the connection on your end?

**Comment by silky** [comment]
hahahaha great

it works. thanks!
